######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 2 18:00:41 2015
######################################################################
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets printsupport
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DTW_GUI.h qcustomplot.h
FORMS += DTW_GUI.ui
SOURCES += DTW_GUI.cpp main.cpp qcustomplot.cpp
